### ISSUE TITLE
About how to make it with cmake or (add it into my own c++ project)?

### ISSUE THREAD

**Issue by LiuYi-Up** [Mario-td/Simplified-hand-tracking-with-Mediapipe-CPP#3]
Hello, thank you for your great work.
When I want to add the mediapipe hand tracking to my own cpp project(on Linux ), it comfuses me that I dont't know how to do and how to make it with cmake.
It's surprised me that meet your work here, so I wish you can provide me some sugestions.
Hope your reply. Best wishes!

**Comment by Mario-td** [comment]
Sorry that I cannot help you with that. 
This project is built entirely with bazel. 
You could try creating a dynamic or static library with bazel and then use it with cmake.
